hanges[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.29.0"

[programs.localnet]
vaiiya_lottery = "G4UEe8pGH9LzvpbtyLRTMV5PWnT6S5g9nqjNiW6CUB6R"

[programs.devnet]
vaiiya_lottery = "G4UEe8pGH9LzvpbtyLRTMV5PWnT6S5g9nqjNiW6CUB6R"

[programs.mainnet]
vaiiya_lottery = "G4UEe8pGH9LzvpbtyLRTMV5PWnT6S5g9nqjNiW6CUB6R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "server-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/*"
]

[test]
startup_wait = 10000
shutdown_wait = 0

[test.validator]
url = "https://api.mainnet-beta.solana.com"
